# NumPy Arrays


**python objects:** 

1. high-level number objects: integers, floating point
2. containers: lists (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

# 1. Creating arrays

In [2]:
#1-D
import numpy as np

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [3]:
a.ndim

1

In [4]:
a.shape

(4,)

In [5]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b
#print dimenstions
print(b.ndim)

#print shape of the array
print(b.shape)

2
(2, 3)


** 1.2  Functions for creating arrays**

In [6]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#using linspace

a = np.linspace(0, 1, 6) #start, end, number of points

a

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [42]:
#common arrays

a = np.ones((3, 3))

a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
b = np.zeros((3, 3))

b

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [11]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [12]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [45]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 

a

array([ 0.64068134,  0.67317563,  0.19382549,  0.83460786])

# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:


In [14]:
a = np.arange(10)

a.dtype

dtype('int64')

In [15]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [49]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [17]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [18]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


# Elementwise Operations

**1. Basic Operations**

**with scalars**

In [19]:
a = np.array([1, 2, 3, 4]) #create an array

a + 1

array([2, 3, 4, 5])

In [20]:
a ** 2

array([ 1,  4,  9, 16])

In [21]:
#multiplication

c = np.diag([1, 2, 3, 4])

c*c

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

**Logical Operations**

In [22]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False], dtype=bool)

In [23]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_and(a, b)

array([ True, False, False, False], dtype=bool)

**Transcendental functions:**

In [55]:
a = np.arange(5)

np.sin(a) 

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [56]:
np.log(1)

0.0

In [57]:
np.exp(a)   #evaluates e^x for each element in a given input

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

# Basic Reductions

**computing sums**

In [27]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [28]:
#sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [29]:
x.sum(axis=0)

array([3, 3])

**Other reductions**

In [61]:
x = np.array([[1, 3, 2], [0, 2, 4]])
x.min()

0

In [68]:
x.max()

4

In [69]:
x.argmin()# index of minimum element

3

In [70]:
x.argmax()

5

# Array Shape Manipulation

**Flattening**

In [34]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [35]:
a.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

**Reshaping**

The inverse operation to flattening:

In [36]:
a.shape

(2, 3)

In [37]:
b = a.ravel()

In [38]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

**Sorting Data**

In [39]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [40]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [41]:
#Finding indexes of minima and maxima:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

(0, 2)